stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm run install-client
    artifacts:
        expire_in: 1 week
        paths:
            - client/node_modules

deploy:
    stage: deploy
    script:
        - npm run start-client
