notifications:
    slack: webapps112017:FjI7aS4lUyb5ZeRmZGdDKJVV

language: node_js
node_js:
  - "6.1"

cache:
  directories:
    - "node_modules"

install:
  - cd app && npm install && cd ..
  - cd client && npm install

script:
  - webpack -p && cd ..

deploy:
  provider: heroku
  api_key:
    secure: "aa01864e-de10-465b-8de2-5e1f6b46b616"
  app: ai-fights
  skip_cleanup: true
