notifications:
    slack: webapps112017:FjI7aS4lUyb5ZeRmZGdDKJVV

language: node_js
node_js:
  - "6.1"

cache:
  directories:
    - "node_modules"

install:
  - cd client && npm install

script:
  - webpack
